// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'App-logo': string;
  'App-logo-spin': string;
  'boink': string;
  'bounce': string;
  'container': string;
  'desk': string;
  'email': string;
  'form': string;
  'formEntry': string;
  'links': string;
  'message': string;
  'name': string;
  'navbar': string;
  'navbar__links': string;
  'page': string;
  'pageTitle': string;
  'page__current': string;
  'page__wrapper': string;
  'post': string;
  'post-enter': string;
  'post-enter-active': string;
  'post-exit': string;
  'post-exit-active': string;
  'post__btns': string;
  'root': string;
  'secondaryTitle': string;
  'stretch': string;
  'stretch2': string;
  'stretch3': string;
  'submit': string;
  'termsConditions': string;
  'title': string;
  'title-Tag-Line': string;
}
export const cssExports: CssExports;
export default cssExports;
